// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwsUoLb6jW226c4idyPArgRXSrKqcqMzQ',
    appId: '1:163694862456:web:e4ac5f11c8491f547ecd8d',
    messagingSenderId: '163694862456',
    projectId: 'mosaiccapp',
    authDomain: 'mosaiccapp.firebaseapp.com',
    storageBucket: 'mosaiccapp.appspot.com',
    measurementId: 'G-D5KF9Y4C8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD34wHRx6eFvEKe7EmEE-BtNeV5c_WDoCk',
    appId: '1:163694862456:android:d54fbadd15bbc1857ecd8d',
    messagingSenderId: '163694862456',
    projectId: 'mosaiccapp',
    storageBucket: 'mosaiccapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWOHGY9upMfQzdVzd_vRhgOH1s8yAtmxU',
    appId: '1:163694862456:ios:f3c15d8671d074337ecd8d',
    messagingSenderId: '163694862456',
    projectId: 'mosaiccapp',
    storageBucket: 'mosaiccapp.appspot.com',
    iosClientId: '163694862456-th8ilujncq4ktm73dordss4to4nejjim.apps.googleusercontent.com',
    iosBundleId: 'com.example.mosaicc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWOHGY9upMfQzdVzd_vRhgOH1s8yAtmxU',
    appId: '1:163694862456:ios:f3c15d8671d074337ecd8d',
    messagingSenderId: '163694862456',
    projectId: 'mosaiccapp',
    storageBucket: 'mosaiccapp.appspot.com',
    iosClientId: '163694862456-th8ilujncq4ktm73dordss4to4nejjim.apps.googleusercontent.com',
    iosBundleId: 'com.example.mosaicc',
  );
}
